### ISSUE TITLE
Get submodule info?

### ISSUE THREAD

**Issue by fsmikedev** [devlooped/GitInfo#105]
Hi, 

How can I get submodule information? I'd like to gather information regarding our submodules, it looks like the msbuild targets only work from the root .git folder.

Thanks.

**Comment by phnx47** [comment]
Should check .git file
Inside file info where gitdir: `gitdir: ../.git/modules/{name}`

**Comment by phnx47** [comment]
I found in code
```
		<!-- Determine the .git dir. In the simple case, this is just $(GitRoot)\.git.
         But in the case of submodules, a .git *file* rather than a directory 
         will be present at that path, with a value like:
              gitdir: ../../.git/modules/external/toq
         Which points to the actual folder where the git info exists in the containing 
         repository. -->
		<PropertyGroup>
			<GitDir>$([System.IO.Path]::Combine('$(GitRoot)', '.git'))</GitDir>
			<_IsGitFile>$([System.IO.File]::Exists('$(GitDir)'))</_IsGitFile>
		</PropertyGroup>
```
But it is doesn't work for me in TeamCity. I think I should check everything in my build scripts

**Comment by kzu** [comment]
r u sure TeamCity is checking out your submodules too? This works and is in use in Xamarin in a lot of places, with submodules and all (although not on TeamCity, mostly Azure DevOps)

**Comment by kzu** [comment]
Closing stale issue for now. Plz reopen as needed.
