### ISSUE TITLE
Do not assume the repository have remote "origin"

### ISSUE THREAD

**Issue by CCRcmcpe** [devlooped/GitInfo#142]
I renamed repository remote "origin" to "github" because I have two remotes, then I get a build warning:
```
1>C:\Users\Rcmcpe\.nuget\packages\gitinfo\2.1.2\build\GitInfo.targets(406,3): warning : Could not retrieve repository url for remote 'origin'
```
And then the MSBuild property `$(GitRepositoryUrl)` is empty, `$(GitBaseVersion)` is also empty (Don't know whether this is related to the warning).

**Comment by kzu** [comment]
See https://github.com/devlooped/GitInfo/blob/main/src/GitInfo/build/GitInfo.targets#L26-L27

You can set `GitRemote` on your csproj and fix that.

**Comment by CCRcmcpe** [comment]
OK, thanks!
