### ISSUE TITLE
Feature request: let _CommitDateFormat be configurable

### ISSUE THREAD

**Issue by tomcurran** [devlooped/GitInfo#144]
It would be great if different git commit date formats could be configured in place of the original. For example, I'd like to use `%ct` instead of `%cI` sometimes. Thanks!

**Comment by kzu** [comment]
Could you provide some example of how this would be used in a concrete scenario?

Thanks!

**Comment by tomcurran** [comment]
Certainly. We want to use a git commit date unix timestamp as a version number of our xamarin android/ios apps. That could be achieved by adding something like the below for the xamarin android csproj. The functionality is all in GitInfo to achieve this, just that we want to modify the `_CommitDateFormat` variable to use a slightly different value. Hope that helps explain it better.

```
  <Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets" />
  <Target Name="AndroidManifestUpdate">
    <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
      <_CommitDateFormat>%%ct</_CommitDateFormat>
    </PropertyGroup>
    <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
	  <_CommitDateFormat>%ct</_CommitDateFormat>
	</PropertyGroup>
    <XmlPoke XmlInputPath="Properties\AndroidManifest.xml" Namespaces="&lt;Namespace Prefix='android' Uri='http://schemas.android.com/apk/res/android' /&gt;" Query="manifest/@android:versionCode" Value="$(GitCommitDate)" />
  </Target>
```

**Comment by kzu** [comment]
Sounds good. Would you like to take a shot at a PR that introduces a public property `GitCommitDateFormat` that enables this scenario?

Thanks!

**Comment by tomcurran** [comment]
I've taken a shot at a PR #145 Wasn't sure how to run and test it but it must be pretty close to a solution.
