### ISSUE TITLE
GitThisAssemblyMetadata documentation is confusing

### ISSUE THREAD

**Issue by Jehoel** [devlooped/GitInfo#152]
The documentation for `GitThisAssemblyMetadata` is a tad confusing because of the use of double-negatives and the word "only". To a lesser extent the documentation for `GitThisAssembly` could be improved too.

[Currently it's this](https://github.com/devlooped/GitInfo/blob/46131847c9f27700c94b5cadd9abb1da13265ef7/src/GitInfo/build/GitInfo.targets):

> `$(GitThisAssembly)`:  
> set to 'false' to prevent assembly metadata and constants generation.
> 
> `$(GitThisAssemblyMetadata)`:  
> set to 'false' to prevent assembly metadata generation only. Defaults to 'false'.

I propose changing it to this:

> `$(GitThisAssembly)`:  
> * Enables or Disables `class ThisAssembly` for this project's output assembly.  
>   * Set to 'true' to generate `class ThisAssembly` containing const strings.  
>   * Set to 'false' to not generate anything for this project.  
> * Defaults to `false` (i.e. GitInfo is opt-in).
> 
> `$(GitThisAssemblyMetadata)`:  
> * Enables or Disables `[assembly: AssemblyMetadata("GitInfo...")]` for this project's output assembly. Note that the `$(GitThisAssembly)` property must also be set to 'true` for this property to take effect.
>   * Set to 'true' to generate `[assembly: AssemblyMetadata("GitInfo...")]` assembly attributes at compile-time.
>   * Set to 'false' to not generate any `[assembly: AssemblyMetadata("GitInfo...")]` assembly attributes - only `class ThisAssembly` will be generated.
>  * Defaults to 'false' (i.e. `[assembly: AssemblyMetadata("GitInfo...")]` assembly attributes are not generated by default, even when `$(GitThisAssembly)` is enabled).

**Comment by kzu** [comment]
makes perfect sense, love the proposed change.

**Comment by Jehoel** [comment]
@kzu I submitted a PR - any issues so far?
