### ISSUE TITLE
Bamboo version missmatch?

### ISSUE THREAD

**Issue by SpiritBob** [devlooped/GitInfo#162]
After tinkering a lot in my repository by adding/removing tags and GitInfo.txt files, now for some unknown reason everything works correctly and as expected locally, but when Bamboo checkouts the branch, it provides vastly different version numbers than you'd expect.

Any ideas what's going on here? I tried clearing the build after each successful run of the buld job, but it didn't help. I made sure that there wasn't any GitInfo.txt files lying around in there. Currently I'm using tags. I'm expecting to see version 1.0.0.1 where the last number is $GitCommits variable, but instead I see something like 2.0.0.7.

I cloned the repository several times and it always yielded the expected 1.0.0.1, so I have no idea what's going on here.

EDIT: After inspecting, it seems SVN is used there, and for some reasons, none of the tags were deleted it seems, so it got confused along the way. Is there a way to force re-syncing of tags in the SVN repository?

Using ``git tag -l`` there yields all of the created tags, but in reality, most of them are actually deleted in the repository.

**Comment by kzu** [comment]
No idea about what bamboo uses, but if SVN is involved, it most certainly seems unrelated to GitInfo. Your clocks try some other alternatives like GitVersion and you should be able to reproduce the same issues with that, if it indeed is an external issue.

**Comment by SpiritBob** [comment]
Seems the issue is with tagging itself. I didn't know that when you delete a tag, other people that've cloned the repo need to also manually delete it.
