### ISSUE TITLE
Build fails if `git config log.showSignature true`

### ISSUE THREAD

**Issue by corbob** [devlooped/GitInfo#180]
## Describe the Bug

I'm trying to build https://github.com/chocolatey/docs using the `preview.ps1` script that fires off a cake build process that uses GitInfo. If I have `log.showSignature` set to `true`, it will fail for any commit that is signed by me, but it will succeed when built off of the master branch which has a most recent commit signed by GitHub web-runner. If I turn this setting off the build succeeds.

This appears to be the same issue as https://github.com/devlooped/GitInfo/issues/86 with the caveat that it only seems to fail with my signed commits and no other signed commits... It also occurs for me on both Windows and MacOS.

## Steps to Reproduce

1. clone https://github.com/corbob/docs and checkout `sensitive_parameters`
2. run `git config --add log.showSignature true`
3. run `.\preview.ps1` (or `./preview.sh` if you're not using PowerShell)
4. wait for `Statiq-Preview` to fail
5. run `git checkout master`
6. run `.\preview.ps1` and notice that the command succeeds this time.

When it errors, it errors on line 56 in `./obj/Release/netcoreapp3.1/ThisAssembly.GitInfo.g.cs` and line 56 will look something like this:
```csharp
      public const string CommitDate = @"gpg: Signature made Wed Oct 27 09:37:45 2021 PDT;gpg:                using RSA key 77C181910F0BE28DDA950F6960EA5F548E62319A;gpg: Good signature from "Cory Knox <cory@knoxy.ca>" [ultimate];gpg:                 aka "Cory Knox <me@coryknox.dev>" [ultimate];gpg:                 aka "Cory Knox <corbob@knoxy.ca>" [ultimate];2021-10-27T09:37:45-07:00";
```
instead of like this:
```csharp
      public const string CommitDate = @"2021-10-27T09:47:05-07:00";
```

## Expected Behavior

The build is expected to succeed.

## Exception with Stack Trace

No exception occurs, just build failure due to Syntax errors.

## Version Info

GitInfo version 2.1.2 (I have verified that this also occurs for me on 2.2.0)

Statiq.Web 1.0.0-beta.33

**Comment by socram8888** [comment]
Fix provided in #213
