### ISSUE TITLE
Git isDirty triggers rebuilds

### ISSUE THREAD

**Issue by laurenceSaes** [devlooped/GitInfo#183]
## Describe the Bug

The isDirty flag triggers a rebuild on projects that depend on GitInfo. This is even for projects that do not make use of the dirty property. The value is also quite often incorrect, which makes it useless. 

Is there an option to ignore the isDirty flag? 

## Steps to Reproduce

Make use of GitInfo and rebuild a project. The compiler rebuilds the project when the dirty flag has incorrectly changed.

## Expected Behavior

That it is possible to disable isDirty and that the flag is not incorrectly true or false.

## Version Info

2.2.0

**Comment by kzu** [comment]
Fixed in #184
