### ISSUE TITLE
Branch name is wrong when compiling from a git worktree

### ISSUE THREAD

**Issue by itainice** [devlooped/GitInfo#189]
## Describe the Bug
Using Visual Studio 2017 enterprise.
Create a new worktree and checkout some branch to that worktree.
Open/Compile my project from a worktree.
Visual Studio shows the correct branch name, but GitInfo has a wrong branch name.
## Expected Behavior
Expecting to haver the correct branch name in ThisAssembly.Git.Branch.

The (wrong) branch name is probably taken from .git/HEAD of the main branch,. The correct value is in .git/worktrees/WorktreeName/HEAD .

**Comment by kzu** [comment]
I haven't encountered any usage of worktrees, so I don't know how important that feature is.

I'd accept a PR if provided. 

Thanks!

**Comment by itainice** [comment]
Just got version 2.3.0 and it looks OK.
I'll give it some more testing before closing the issue.

**Comment by kzu** [comment]
Closing for now, seems to be working as expected.
