### ISSUE TITLE
Version issue with Multi-target projects

### ISSUE THREAD

**Issue by kikaragyozov** [devlooped/GitInfo#202]
If I have a normal project that only targets one framework, and I define the following target in its `.csproj` file:

```
  <Target Name="PopulateNETSDKAssemblyVersion" AfterTargets="_GitPopulateVersionInfo">
    <PropertyGroup>
      <Version>$(GitBaseVersionMajor).$(GitBaseVersionMinor).$(GitBaseVersionPatch).0</Version>
      <FileVersion>$(GitBaseVersionMajor).$(GitBaseVersionMinor).$(GitBaseVersionPatch).$(GitCommits)</FileVersion>
      <PackageVersion>$(FileVersion)</PackageVersion>
      <InformationalVersion>$(FileVersion)+branch.$(GitBranch).commit.$(GitCommit)</InformationalVersion>
    </PropertyGroup>
    <Message Importance="high" Text="PackageVersion: $(PackageVersion)" />
  </Target>
```

Everything works - when packing the version it's correct. But once we move to a multi-target project, this doesn't do anything.

**Comment by kzu** [comment]
Change it to this:

```xml
<Target Name="PopulateNETSDKAssemblyVersion" BeforeTargets="CoreCompile;GenerateNuspec" DependsOnTargets="GitVersion">
```

When multi-targeting, the .NET SDK won't invoke most of the "normal" targets it does for a regular build. You can learn a lot by running `dotnet build -bl` on the projects and using msbuildlog.com to inspect the targets that are being run and when.
