### ISSUE TITLE
GitInfo generates empty namespace in some cases

### ISSUE THREAD

**Issue by Pilvinen** [devlooped/GitInfo#230]
## Version Info

GitInfo 2.3.0
Godot Game Engine 3.5.1 stable

## Additional Info

I'm on a little bit of a fishing trip here. I'm not sure if this is shortcoming in GitInfo or not, but I'll report this here anyway and see what happens. I'm a bit of a newbie, and couldn't track this issue down any more than what I discovered below. Maybe it's helpful or maybe it's not.

GitInfo package errors out with Godot Game Engine because `/.mono/temp/obj/Debug/ThisAssembly.GitInfo.g.cs` doesn't get a namespace for some reason:

"`modules/mono/glue/gd_glue.cpp:249 - Failed to determine namespace and class for script: res://.mono/temp/obj/Debug/ThisAssembly.GitInfo.g.cs. Parse error: Unexpected token: {`"

This failure to get the namespace results in generated code where the code reads:
```csharp
namespace 
{
	// code
}
```

And obviously this gives an error.

Adding GitInfo package specific namespace definition to the game project's `.csproj` fixes the error:

```csharp
<ThisAssemblyNamespace>Stowaway</ThisAssemblyNamespace>
```

Adding `RootNamespace` doesn't help.

## Expected behavior

GitInfo should either get the namespace or - I suppose - if i can't for some reason, it should just fill in "gitinfo.foo" or something as the namespace so that it doesn't generate code with no namespace defined and error out.

## Additional notes

Even though there's the error, GitInfo actually seems to work as far as I can tell.

**Comment by kzu** [comment]
Any chance you could try the latest 3.0.0 beta, which switches to a far better, source generator-based approach for C# when you're not customizing the namespace?

**Comment by kzu** [comment]
Also, could you check the generated file at the top? The template contains:

```csharp
// <auto-generated />
#define $NamespaceDefine$
#pragma warning disable 0436

#if LOCALNAMESPACE
namespace _RootNamespace_
{
...
```

The replacement for `$NamespaceDefine$` is:

```xml
      <_ThisAssemblyContent Condition="'$(ThisAssemblyNamespace)' != ''">$(_ThisAssemblyContent.Replace('$NamespaceDefine$', 'LOCALNAMESPACE'))</_ThisAssemblyContent>
      <_ThisAssemblyContent Condition="'$(ThisAssemblyNamespace)' == ''">$(_ThisAssemblyContent.Replace('$NamespaceDefine$', 'GLOBALNAMESPACE'))</_ThisAssemblyContent>
```

Therefore, if `ThisAssemblyNamespace` where empty, it would cause the define to *not* contain the `LOCALNAMESPACE` value required for the `namespace ... {` to be considered by the compiler.

So, even if we do have an unconditional replace with the property value with:

```xml
      <_ThisAssemblyContent>$(_ThisAssemblyContent.Replace('_RootNamespace_', '$(ThisAssemblyNamespace)'))</_ThisAssemblyContent>
```

The `Define` should take care of the conditional compilation as needed 🤔

**Comment by kzu** [comment]
Perhaps a binlog + wrong .cs when it fails would help troubleshoot?

**Comment by kzu** [comment]
Closing for now due to inaction. Please reopen if you can provide a binlog or of this still fails on the latest version.

Thanks!
