### ISSUE TITLE
Migration from v2 -> v3

### ISSUE THREAD

**Issue by Lonli-Lokli** [devlooped/GitInfo#240]
## Describe the Bug

What are the steps I should perform to migrate to the version 3?

## Steps to Reproduce

```c#
public class ReproTest
{
  [Fact]
  public void Repro()
  {
    // arrange
    // act
    // assert
  }
}
```

## Exception with Stack Trace

```text
Put the exception with stack trace here.
```

**Comment by kzu** [comment]
None, everything should Just Work as always.

If something isn't, plz file a bug 🙏 . Thanks!

**Comment by Lonli-Lokli** [comment]
My code just do not compile with strange error, can it be treated as bug? ;)

**Comment by kzu** [comment]
If you provide a clean repro and/or a binlog, sure!

**Comment by Lonli-Lokli** [comment]
@kzu Here is it
https://gitlab.com/lonli.lokli/cv-app/-/tree/renovate/gitinfo-3.x/backend/cv-api
[msbuild.zip](https://github.com/devlooped/GitInfo/files/10778290/msbuild.zip)

**Comment by kzu** [comment]
Ok, found the root cause and [have a fix](https://github.com/devlooped/GitInfo/pull/248). GitInfo now sets `<Version>` by default, but you can turn that off to get the legacy behavior by setting `GitVersion=false`.

**Comment by kzu** [comment]
Tried the new CI build on the provided repo with GitInfo version `42.42.206-main` and the following to restore from the CI feed:

```xml
    <PropertyGroup>
        ...
        <RestoreSources>https://pkg.kzu.io/index.json;https://api.nuget.org/v3/index.json</RestoreSources>
    </PropertyGroup>
```

And it now works as expected. Please reopen if something's off. I'll ship the release ASAP.
