### ISSUE TITLE
SemVer version does not seem to align with GitVersion/GitFlow?

### ISSUE THREAD

**Issue by Simonl9l** [devlooped/GitInfo#261]
## Describe the Bug

I was very exited to find this repo/library as I'm all over code generation! 

I expects I have either a usage error, or expectation gap to have it support [GitFlow SerVer](https://levelup.gitconnected.com/semantic-versioning-with-git-flow-and-the-marvelous-way-to-go-there-b9f97b90455c)

I use [GitVersion](https://github.com/GitTools/GitVersion) tooling elsewhere as it is supported by [Nuke.Build](https://nuke.build) and use GitFlow as my underlying version management approach - not looking for opinions on this.

## Steps to Reproduce

I'm on a brach where a `dotnet GitVersion` returns

```json
{
  "Major": 0,
  "Minor": 3,
  "Patch": 0,
  "PreReleaseTag": "<my branch>.1",
  "PreReleaseTagWithDash": "-<my branch>.1",
  "PreReleaseLabel": "<my branch>",
  "PreReleaseLabelWithDash": "-<my branch>",
  "PreReleaseNumber": 1,
  "WeightedPreReleaseNumber": 30001,
  "BuildMetaData": 11,
  "BuildMetaDataPadded": "0011",
  "FullBuildMetaData": "11.Branch.<my branch>.Sha.0699fef12d910c80273b547a22bdc46227b072a9",
  "MajorMinorPatch": "0.3.0",
  "SemVer": "0.3.0-<my branch>.1",
  "LegacySemVer": "0.3.0-<my branch>1",
  "LegacySemVerPadded": "0.3.0-<my branch>0001",
  "AssemblySemVer": "0.3.0.0",
  "AssemblySemFileVer": "0.3.0.0",
  "FullSemVer": "0.3.0-<my branch>.1+11",
  "InformationalVersion": "0.3.0-<my branch>.1+11.Branch.<my branch>Sha.0699fef12d910c80273b547a22bdc46227b072a9",
  "BranchName": "<my branch>",
  "EscapedBranchName": "<my branch>",
  "Sha": "0699fef12d910c80273b547a22bdc46227b072a9",
  "ShortSha": "0699fef",
  "NuGetVersionV2": "0.3.0-<my branch>0001",
  "NuGetVersion": "0.3.0-<my branch>0001",
  "NuGetPreReleaseTagV2": "<my branch>0001",
  "NuGetPreReleaseTag": "<my branch>0001",
  "VersionSourceSha": "f41e42bb3dae18ef1489638edecc9e62d16c2990",
  "CommitsSinceVersionSource": 11,
  "CommitsSinceVersionSourcePadded": "0011",
  "UncommittedChanges": 13,
  "CommitDate": "2023-02-26"
}
```
However:

`ThisAssembly.Git.SemVer.Major` returns `0`,
`ThisAssembly.Git.SemVer.Minor` returns `1`, and
`ThisAssembly.Git.SemVer.Patch` returns `76` <--this is the same as `ThisAssembly.Git.Commits`

even though: 
`ThisAssembly.Git.SemVer.Source` return `Tag` - My repo has the most recent release tag as `0.2.0`.

My `GitVersion.yml` looks line this:
```yaml
mode: ContinuousDelivery
branches: {}
ignore:
  sha: []
merge-message-formats: {}
```
 ## Expected Behavior

`ThisAssembly.Git.SemVer.Major` returns `0`,
`ThisAssembly.Git.SemVer.Minor` returns `3`, and
`ThisAssembly.Git.SemVer.Patch` returns `0` 

additionally id expect:
`ThisAssembly.Git.SemVer.Label` return `<my branch>`
`ThisAssembly.Git.SemVer.DashLabel` return `-<my branch>`

## Exception with Stack Trace

N/A

## Additional Info

N/A

**Comment by kzu** [comment]
GitInfo does not intend to be compatible with whatever GitVersion generates or emits.

If you run a diagnostic log or open a build log with the msbuildlog.com tool, you can directly see all the calls GitInfo makes to `git` and with what parameters. It's designed *intentionally* to be fully transparent in how it talks to git, and everything is in a single targets file so you can inspect every `<Exec` command issued via MSBuild.

I understand each tool has its own way of doing things, and that's fine.

For example, the tag lookup is located at [GitInfo.targets](https://github.com/devlooped/GitInfo/blob/main/src/GitInfo/build/GitInfo.targets#L746-L846): you can see how we locate the tag.
