### ISSUE TITLE
IsDirty is no more constant

### ISSUE THREAD

**Issue by fabianoriccardi** [devlooped/GitInfo#287]
I had just upgraded GitInfo to v3.0.6. With respect to v2.x, the `IsDirty` flag is no more constant, and I cannot use it to generate the Assembly Metadata. Will you solve this regression?

## Steps to Reproduce

    [assembly: AssemblyInformationalVersion(ThisAssembly.Git.IsDirty ? "dirty" : "")]

## Expected Behavior

It should compile, instead it says that IsDirty is not constant.

## Version Info

GitInfo v3.0.6

**Comment by kzu** [comment]
use `IsDirtyString` instead as a workaround for now

**Comment by kzu** [comment]
Fixed in #288. Shipping in v3.1.0
