### ISSUE TITLE
Build Date

### ISSUE THREAD

**Issue by stephanstapel** [devlooped/GitInfo#309]
Hi,
first of all thanks for this package. It really closes a gap!

I wanted to ask if it is already possible to get the build date (... and I just didn't find it) or if it is possible to add the build date to the library. 

Cheers, Stephan

**Comment by kzu** [comment]
Hi there @stephanstapel! Thanks for the kind words.

The build date would be related to the actual build and not necessarily Git-related. It's fairly easy to stamp the current date as an assembly attribute or even a constant, but I'd look at [ThisAssembly](https://github.com/devlooped/ThisAssembly) for that instead.

After referencing `ThisAssembly.Constants` package, for example, you could add the following via MSBuild:

```xml
  <ItemGroup>
    <Constant Include="BuildDate" Value="$([System.DateTime]::Now.ToString('O')))" />
  </ItemGroup>
```

And you'd get this in the IDE:

![image](https://github.com/devlooped/GitInfo/assets/169707/a354fa1f-dcbe-4f9c-847a-b961112077ae)

**Comment by stephanstapel** [comment]
Thanks, @kzu 
Honestly speaking, this is a bit of black magic for me so excuse my follow up question. I guess there is no way of turning BuildDate into a DateTime object within ThisAssembly.Constants?

**Comment by kzu** [comment]
Perhaps one day 😉 https://github.com/devlooped/ThisAssembly/issues/150

in the meantime, all generated code is partial, so you could get your DateTime with:

```csharp
partial class ThisAssembly
{
  partial class Constants 
  {
     public static DateTime BuildDate => DateTime.Parse(BuildDateString);
  }
}
```

And you'd rename the constant to `BuildDateString`.
