### ISSUE TITLE
ThisAssembly.Git.Commits returns an incorrect value for .NET 6 app

### ISSUE THREAD

**Issue by CyberbobGit** [devlooped/GitInfo#318]
Hi,

first of all thanks for this project!

Since the moment we migrated our project from .NET Framework 4 to .NET 6 (git repository is still the same), we have a problem with an incorrect value in ThisAssembly.Git.Commits. If I take the hash from ThisAssembly.Git.Commit property and try to call in command line:

**git rev-list [TheHash] --count**

I get 17324 while ThisAssembly.Git.Commits contains 1803. Where could be the problem?

Thanks

## Version Info
3.3.3

**Comment by kzu** [comment]
You can run the build with msbuildlog.com and inspect the Exec commands issued by GitInfo to exactly see what git commands are run.

**Comment by kzu** [comment]
Closing for now since there's no additional info to act on. My suggestion is to inspect the executed `git` commands via MSBuild, since those are the ones counted for the commits property.
