### ISSUE TITLE
Projects don't rebuild after committing

### ISSUE THREAD

**Issue by ansteele** [devlooped/GitInfo#322]
## Describe the Bug

Projects don't rebuild following a commit to the current git branch.

## Steps to Reproduce

1. Build a project (managed under git)
2. Make a change unrelated to that project (not a source file within that project)
3. Commit the change to the current git branch
4. Hit build on the project

Using this as our property sheet:
```xml
<Target Name="PopulateInfo" BeforeTargets="CoreCompile;GetAssemblyVersion;GenerateNuspec;GetPackageContents">
    <PropertyGroup>
	<Version>$(GitSemVerMajor).$(GitSemVerMinor).$(GitSemVerPatch)</Version>
	<PackageVersion>$(Version)</PackageVersion>
	<FileVersion>$(Version)</FileVersion>
	<RepositoryCommit>$(GitCommit)</RepositoryCommit>
    </PropertyGroup>

    <Error Text="Failed to determine product version" Condition="'$(GitCommit)' == ''" />
</Target>
```

## Expected Behavior

The project rebuilds with a new version (based on git status).

## Exception with Stack Trace

No exception but the project is marked as up-to-date and doesn't rebuild.

## Version Info

GitInfo-3.3.1

## Additional Info

I found https://github.com/devlooped/GitInfo/issues/186 as a similar issue but that seems to deal with switching HEAD rather than moving HEAD forward by committing. (The .git\HEAD file only changes when the branch name/checked out commit changes)

I've got a workaround by adding the git log for HEAD to the MSBuild up-to-date inputs as that file seems to reliably change on commit. 

```xml
<ItemGroup>
    <UpToDateCheckInput Include="$(SolutionDir).git\logs\HEAD" />
</ItemGroup>
```

Thanks :)

**Comment by kzu** [comment]
Would you like to submit a PR so it's properly attributed to you? 🙏

**Comment by kzu** [comment]
The workaround only works if the solution is at the root of a repository. The proper fix would be to leverage the `$(GitRoot)` we already determine via targets, and expose that to the incremental check. See https://github.com/dotnet/project-system/blob/main/docs/up-to-date-check.md for more on how it could be implemented.
