### ISSUE TITLE
Git.Branch always gives [HEAD] for detached HEAD commit.

### ISSUE THREAD

**Issue by ArkaHnat** [devlooped/GitInfo#333]
When I'm trying to use `ThisAssembly.Git.Branch` on detached head it always returns me [HEAD].
I didn't change any options. 
When I run command `git name-rev --refs=refs/heads/* --no-undefined --always SHA1` which is a default it gives correct result.
If my branch isn't detached `ThisAssembly.Git.Branch` also gives me correct result

**Comment by kzu** [comment]
And what would constitute "the correct result" for a Branch property where there's no branch checked out? (Unless I misunderstood the question).

**Comment by ArkadiuszHnat** [comment]
@kzu correct result would be in this case the branch to which the commit belongs

**Comment by kzu** [comment]
A commit can belong to any number of branches. As currently designed, GitInfo reads the HEAD file from .git folder.
