### ISSUE TITLE
ThisAssembly is unavailable (security level) 

### ISSUE THREAD

**Issue by Yari27** [devlooped/GitInfo#347]
## Describe the Bug
CS0122	'Element „ThisAssembly” is unavailable due to its security level.
![image](https://github.com/devlooped/GitInfo/assets/10603967/a38fa8dc-4bdd-40c1-9fed-91a4d3c07351)

## Steps to Reproduce
Add ThisAssembly to AssemblyInfo.cs

```c#
[assembly: AssemblyInformationalVersion(ThisAssembly.Git.BaseTag + "-" + ThisAssembly.Git.Commit)]
```
![image](https://github.com/devlooped/GitInfo/assets/10603967/06e40967-778c-454a-b43d-dcdd5f0b1c27)

## Expected Behavior
Has access to ThisAssembly and successful build.

## Exception with Stack Trace

```text
Put the exception with stack trace here.
```

## Version Info
.Net Framework 4.8
GitInfo 3.3.5

**Comment by kzu** [comment]
Plz provide a clean repro attached as a zip (or alternatively, a public repo with the same).

**Comment by Yari27** [comment]
[WindowsFormsAppGitInfoTest.zip](https://github.com/devlooped/GitInfo/files/15499312/WindowsFormsAppGitInfoTest.zip)

**Comment by kzu** [comment]
[WindowsFormsAppGitInfoTest.zip](https://github.com/user-attachments/files/15543007/WindowsFormsAppGitInfoTest.zip)

The project and nuget packages format are effectively legacy. After running the VS upgrade assistant (right-click on project, click Upgrade, after installing the tool from https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.upgradeassistant), the project compiles and can annotate the assembly as shown, without errors.

I'd strongly suggest moving away from legacy project format ASAP. Supporting it is not planned.

Thanks!
