### ISSUE TITLE
Unexpected characters in Git.Branch for annotated tags

### ISSUE THREAD

**Issue by markfinal** [devlooped/GitInfo#71]
Please find attached a VS2015 example as a simple reproducible
[GitInfoAnnotatedTag.zip](https://github.com/kzu/GitInfo/files/2146915/GitInfoAnnotatedTag.zip)

This has a C# console application, and depends on the GitInfo package (v2.0.11). There is a git repo for the project, with 3 commits on it, and start in the master branch.
Build and run the application. The console/debug output should be

`Git branch is 'master'`

Now, in a git bash console (or similar), make an annotated tag, e.g.

`git tag -a hello -m world`

and checkout to the tag

`git checkout hello`

Rebuild the application, and run again. The output is

`Git branch is 'tags/hello^0'`

The trailing `^0` only seems to appear for annotated tags.

**Comment by kzu** [comment]
Ages later, here I'm asking again if this works now as expected 🙏. Seems like it does?

I'm trying to be more active with my oss projects nowadays, so hopefully it won't be another 3 years before I reply 🤦‍♂️
