### ISSUE TITLE
support for git worktree

### ISSUE THREAD

**Issue by namtab00** [devlooped/GitInfo#88]
$(GitBranch) has incorrect (default?) value of **master** when the GitInfo targets are invoked inside a [git worktree](https://git-scm.com/docs/git-worktree/2.20.0#_details).

**Comment by namtab00** [comment]
@kzu Hi, sorry for the ping.. Are you still supporting this repo?

**Comment by kzu** [comment]
Yes, I am. But for cases like this, I'd gladly take a PR. It's not high on my list and it seems to be a sparingly used feature (git worktree I mean). I've never used it myself in any of the git repositories I work on (or contribute to).

**Comment by kzu** [comment]
There doesn't seem to be high interest in this particular enhancement. Please do reopen and we'd welcome a PR if this is still important to you.

Thanks!
