### ISSUE TITLE
GitInfo.cache collects warnings which leads to build errors

### ISSUE THREAD

**Issue by AOrazaev** [devlooped/GitInfo#91]
Hi, this is not the first time I hit this issue with GitInfo. First time and probably this time I'll fix git warning and will not have problem, but still its possible to hit it from time to time.

In our repo describe tags prints warning
```
$ git describe --tags
warning: tag 'refs/tags/Cloud_1.0_Deployment' is really 'Cloud_1.0_Deployment' here
refs/tags/Cloud_1.0_Deployment-99-g9500e448
```

As a result GitInfo.cache has tag info which look like this:
```
GitTag=warning: tag 'refs/tags/Cloud_1.0_Deployment' is really 'Cloud_1.0_Deployment' here;refs/tags/Cloud_1.0_Deployment-99-g9500e448;
GitBaseTag=refs/tags/Cloud_1.0_Deployment;warning: tag 'refs/tags/Cloud_1.0_Deployment' is really 'Cloud_1.0_Deployment' here;
```

Which leads to build error.

**Comment by kzu** [comment]
If you're not using the tags for versioning, you can turn off tag processing entirely [GitIgnoreTagVersion](https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.targets#L44-L47). Or do you still use some tags for versioning and also for other purposes simulateously?

**Comment by AOrazaev** [comment]
As I said, I proceeded with fixing warning in git. But this is just a workaround as the suggested method with ignoring tags.

Warning shouldn't be parsed as a tag information.

**Comment by kzu** [comment]
We now provide `$(GitTagRegex)` which is passed to `git describe --tags --match` to filter out the ones you don't want (defaults to `*`). We also always validate the tag against the version regex, so the error should be obvious too.
